# fly.toml app configuration file generated for fistbump-server on 2023-09-07T19:11:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fistbump-server"
primary_region = "mad"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
